### PR TITLE
Make passing PHP 7 tests mandatory

### PR DESCRIPTION
**Pull request by freekmurze**
PHP 7 is just around the corner. Let's make sure your package is ready from day 1.

### CODE REVIEW

**Comment by hannesvdvreken** [comment]
I will merge this in once PHP 7 is released, ok?

**Comment by freekmurze** [comment]
:+1:

**Comment by hannesvdvreken** [comment]
Thanks. Forgot about this.

**Comment by freekmurze** [comment]
Np. Welcome in the future!

**Pull request merged**
