### PR TITLE
allow config to be set via environment variables

### PR DESCRIPTION
**Pull request by tomschlick**
### Added

* Laravel config file uses environment variables

### CODE REVIEW

**Comment by hannesvdvreken** [comment]
As far as I know `env` is a Laravel specific global function. In order to be usable for all PHP applications it would be nice to use `getenv` instead.

**Comment by tomschlick** [comment]
Thats true, but it looks like currently nothing but Laravel is using that config file... If you setup your own integration they would have to inject the account credentials anyway. 

They most likely wouldn't use that config file but would use their own framework/spaghetti's code's method of storing credentials.

**Comment by hannesvdvreken** [comment]
That is correct. Though `env` is only available in Laravel 5+, and this is supposed to work in L4 too. Sorry :-/

**Comment by hannesvdvreken** [comment]
@tomschlick why don't you update the use of the `env` function to the use of the php native `getenv` function?

**Comment by tomschlick** [comment]
Done!

**Comment by hannesvdvreken** [comment]
:+1:

**Comment by bburr** [comment]
``getenv`` only accepts one argument, the variable name. You'll need to remove passing the default value to this function.

**Comment by hannesvdvreken** [comment]
Right, thanks! I'll update this.

**Comment by bburr** [comment]
:+1:

**Comment by hannesvdvreken** [comment]
@bburr https://github.com/aloha/laravel-twilio/commit/1f1a9954771a69272145e46875ec954bbe96b5d4

**Pull request merged**
