### PR TITLE
Twilio 4.x

### PR DESCRIPTION
**Pull request by hannesvdvreken**

### CODE REVIEW

**Comment by cjmartino** [comment]
Any change of merging this into a new release? As the old one doesn't support php 7.1>

**Comment by billda** [comment]
Waiting for this one as well - any chance it can get merged into master?

**Comment by stueynet** [comment]
Has anyone done extensive testing of this PR? We are going to fork and patch it in.

**Comment by hannesvdvreken** [comment]
@reedmaniac whad'ya think? Merge this?

**Comment by reedmaniac** [comment]
There are no new tests written, but it worked when I did the manual testing locally.  That was two months ago, so I would not mind if someone else gave it a try too as I am not going to get to those any time soon.

**Comment by coffe4u** [comment]
This is becoming a more important update every day. I suggest that this gets the highest priority possible for this repo. Works in my local testing.

**Comment by hannesvdvreken** [comment]
🤷‍♂️

**Comment by hannesvdvreken** [comment]
@coffe4u @reedmaniac @stueynet @cjmartino upgrade to ^4.0 of this package and let me know (read: send a PR) if anything breaks.

**Comment by coffe4u** [comment]
@hannesvdvreken thank you! Will follow up with messages and PRs if we find any issues.

**Pull request merged**
